package ru.traphouse.model.event;

public enum InteractionEventType {
    ARTHUR_ENTERED_FOLLOWING,
    ARTHUR_SAW_TWO_HEADED_PERSON,
    TWO_HEADED_PERSON_RECLINED_IN_CHAIR,
    FEET_PLACED_ON_CONTROL_PANEL,
    LEFT_HAND_PICKS_RIGHT_HEAD_TEETH,
    LEFT_HEAD_SMILED_WIDELY,
    ARTHUR_NOTICED_ANOTHER_UNBELIEVABLE_THING,
    ARTHUR_JAW_DROPPED
}
